/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as RisksRiskIdRouteImport } from './routes/risks.$riskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRiskIdRoute = RisksRiskIdRouteImport.update({
  id: '/$riskId',
  path: '/$riskId',
  getParentRoute: () => RisksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/risks': typeof RisksRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/risks': typeof RisksRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/evidence': typeof EvidenceRoute
  '/risks': typeof RisksRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/risks/$riskId': typeof RisksRiskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/risks'
    | '/vendors'
    | '/risks/$riskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/risks'
    | '/vendors'
    | '/risks/$riskId'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/controls'
    | '/evidence'
    | '/risks'
    | '/vendors'
    | '/risks/$riskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  ControlsRoute: typeof ControlsRoute
  EvidenceRoute: typeof EvidenceRoute
  RisksRoute: typeof RisksRouteWithChildren
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks/$riskId': {
      id: '/risks/$riskId'
      path: '/$riskId'
      fullPath: '/risks/$riskId'
      preLoaderRoute: typeof RisksRiskIdRouteImport
      parentRoute: typeof RisksRoute
    }
  }
}

interface RisksRouteChildren {
  RisksRiskIdRoute: typeof RisksRiskIdRoute
}

const RisksRouteChildren: RisksRouteChildren = {
  RisksRiskIdRoute: RisksRiskIdRoute,
}

const RisksRouteWithChildren = RisksRoute._addFileChildren(RisksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  ControlsRoute: ControlsRoute,
  EvidenceRoute: EvidenceRoute,
  RisksRoute: RisksRouteWithChildren,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
